LANGUAGE_CHOICES = [
    ("brithenig (bzt)", "brithenig (bzt)"),
    ("dżuhuri (jdt)", "dżuhuri (jdt)"),
    ("esperanto (eo)", "esperanto (eo)"),
    ("esperanto (morfem) (eom)", "esperanto (morfem) (eom)"),
    ("ewe (ee)", "ewe (ee)"),
    ("hindi (hi)", "hindi (hi)"),
    ("ido (io)", "ido (io)"),
    ("interlingua (ia)", "interlingua (ia)"),
    ("inuktitut (iu)", "inuktitut (iu)"),
    ("jèrriais (roa)", "jèrriais (roa)"),
    ("jidysz (yi)", "jidysz (yi)"),
    ("ladino (lad)", "ladino (lad)"),
    ("lingala (ln)", "lingala (ln)"),
    ("lojban (jbo)", "lojban (jbo)"),
    ("novial (nov)", "novial (nov)"),
    ("papiamento (pap)", "papiamento (pap)"),
    ("pitjantjatjara (pjt)", "pitjantjatjara (pjt)"),
    ("polski język migowy (pjm)", "polski język migowy (pjm)"),
    ("quenya (qya)", "quenya (qya)"),
    ("sanskryt (sa)", "sanskryt (sa)"),
    ("slovio (slovio)", "slovio (slovio)"),
    ("sranan tongo (srn)", "sranan tongo (srn)"),
    (
        "termin obcy w języku polskim (pl-foreign)",
        "termin obcy w języku polskim (pl-foreign)",
    ),
    ("tetum (tet)", "tetum (tet)"),
    ("tok pisin (tpi)", "tok pisin (tpi)"),
    ("tupinambá (tpn)", "tupinambá (tpn)"),
    ("użycie międzynarodowe (inter)", "użycie międzynarodowe (inter)"),
    ("volapük (vo)", "volapük (vo)"),
    ("znak chiński (zh-char)", "znak chiński (zh-char)"),
    ("język !o!kung (vaj)", "język !o!kung (vaj)"),
    ("język !Xóõ (nmn)", "język !Xóõ (nmn)"),
    ("język abazyński (cau)", "język abazyński (cau)"),
    ("język abchaski (ab)", "język abchaski (ab)"),
    ("język abenaki (abe)", "język abenaki (abe)"),
    ("język adygejski (ady)", "język adygejski (ady)"),
    ("język afar (aa)", "język afar (aa)"),
    ("język afrykanerski (af)", "język afrykanerski (af)"),
    ("język ajmara (ay)", "język ajmara (ay)"),
    ("język akadyjski (akk)", "język akadyjski (akk)"),
    ("język aklanon (akl)", "język aklanon (akl)"),
    ("język alabama (akz)", "język alabama (akz)"),
    ("język albański (sq)", "język albański (sq)"),
    ("język alemański (als)", "język alemański (als)"),
    ("język aleucki (ale)", "język aleucki (ale)"),
    ("język amharski (am)", "język amharski (am)"),
    ("język angielski (en)", "język angielski (en)"),
    ("język arabski (ar)", "język arabski (ar)"),
    ("język aragoński (an)", "język aragoński (an)"),
    ("język aramejski (arc)", "język aramejski (arc)"),
    ("język arapaho (arp)", "język arapaho (arp)"),
    ("język arumuński (roa-rup)", "język arumuński (roa-rup)"),
    ("język asamski (as)", "język asamski (as)"),
    ("język asturyjski (ast)", "język asturyjski (ast)"),
    ("język awarski (av)", "język awarski (av)"),
    ("język azerski (az)", "język azerski (az)"),
    ("język bambara (bm)", "język bambara (bm)"),
    ("język banjumasański (map-bms)", "język banjumasański (map-bms)"),
    ("język baskijski (eu)", "język baskijski (eu)"),
    ("język baszkirski (ba)", "język baszkirski (ba)"),
    ("język bawarski (bar)", "język bawarski (bar)"),
    ("język beludżi (bal)", "język beludżi (bal)"),
    ("język bengalski (bn)", "język bengalski (bn)"),
    ("język białoruski (be)", "język białoruski (be)"),
    (
        "język białoruski (taraszkiewica) (be-tarask)",
        "język białoruski (taraszkiewica) (be-tarask)",
    ),
    ("język birmański (my)", "język birmański (my)"),
    ("język boloński (egl)", "język boloński (egl)"),
    ("język bośniacki (bs)", "język bośniacki (bs)"),
    ("język bretoński (br)", "język bretoński (br)"),
    ("język bułgarski (bg)", "język bułgarski (bg)"),
    ("język cebuano (ceb)", "język cebuano (ceb)"),
    ("język chakaski (kjh)", "język chakaski (kjh)"),
    ("język chantyjski (kazymski) (kca-k)", "język chantyjski (kazymski) (kca-k)"),
    ("język chantyjski (surgucki) (kca-s)", "język chantyjski (surgucki) (kca-s)"),
    (
        "język chantyjski (szurykszarski) (kca-sz)",
        "język chantyjski (szurykszarski) (kca-sz)",
    ),
    ("język chantyjski (wachowski) (kca-w)", "język chantyjski (wachowski) (kca-w)"),
    ("język chickasaw (nai)", "język chickasaw (nai)"),
    ("język chiński standardowy (zh)", "język chiński standardowy (zh)"),
    ("język chorwacki (hr)", "język chorwacki (hr)"),
    ("język czagatajski (chg)", "język czagatajski (chg)"),
    ("język czamorro (ch)", "język czamorro (ch)"),
    ("język czarnogórski (srp)", "język czarnogórski (srp)"),
    ("język czeczeński (ce)", "język czeczeński (ce)"),
    ("język czeski (cs)", "język czeski (cs)"),
    ("język czirokeski (chr)", "język czirokeski (chr)"),
    ("język czuwaski (cv)", "język czuwaski (cv)"),
    ("język dalmatyński (dlm)", "język dalmatyński (dlm)"),
    ("język dolnoniemiecki (nds)", "język dolnoniemiecki (nds)"),
    ("język dolnołużycki (dsb)", "język dolnołużycki (dsb)"),
    ("język duński (da)", "język duński (da)"),
    ("język dzongkha (dz)", "język dzongkha (dz)"),
    ("język erzja (myv)", "język erzja (myv)"),
    ("język estoński (et)", "język estoński (et)"),
    ("język etruski (ett)", "język etruski (ett)"),
    ("język farerski (fo)", "język farerski (fo)"),
    ("język fenicki (phn)", "język fenicki (phn)"),
    ("język fidżyjski (fj)", "język fidżyjski (fj)"),
    ("język filipino (fil)", "język filipino (fil)"),
    ("język fiński (fi)", "język fiński (fi)"),
    ("język francuski (fr)", "język francuski (fr)"),
    ("język friulski (fur)", "język friulski (fur)"),
    ("język fryzyjski (fy)", "język fryzyjski (fy)"),
    ("język ful (ff)", "język ful (ff)"),
    ("język ga (gaa)", "język ga (gaa)"),
    ("język gagauski (tut)", "język gagauski (tut)"),
    ("język galicyjski (gl)", "język galicyjski (gl)"),
    ("język gaskoński (oci-gsc)", "język gaskoński (oci-gsc)"),
    ("język gocki (got)", "język gocki (got)"),
    ("język grenlandzki (kl)", "język grenlandzki (kl)"),
    ("język gruziński (ka)", "język gruziński (ka)"),
    ("język guarani (gn)", "język guarani (gn)"),
    ("język gudźarati (gu)", "język gudźarati (gu)"),
    ("język gyyz (gez)", "język gyyz (gez)"),
    ("język górnołużycki (hsb)", "język górnołużycki (hsb)"),
    ("język haitański (ht)", "język haitański (ht)"),
    ("język hausa (ha)", "język hausa (ha)"),
    ("język hawajski (haw)", "język hawajski (haw)"),
    ("język hebrajski (he)", "język hebrajski (he)"),
    ("język hiligaynon (hil)", "język hiligaynon (hil)"),
    ("język hiszpański (es)", "język hiszpański (es)"),
    ("język holenderski (nl)", "język holenderski (nl)"),
    ("język hupa (hup)", "język hupa (hup)"),
    ("język ilokano (ilo)", "język ilokano (ilo)"),
    ("język indonezyjski (id)", "język indonezyjski (id)"),
    ("język inguski (inh)", "język inguski (inh)"),
    ("język irlandzki (ga)", "język irlandzki (ga)"),
    ("język islandzki (is)", "język islandzki (is)"),
    ("język istriocki (ist)", "język istriocki (ist)"),
    ("język japoński (ja)", "język japoński (ja)"),
    ("język jawajski (jv)", "język jawajski (jv)"),
    ("język jaćwieski (xsv)", "język jaćwieski (xsv)"),
    ("język joruba (yor)", "język joruba (yor)"),
    ("język kabylski (kab)", "język kabylski (kab)"),
    ("język kakczikel (cak)", "język kakczikel (cak)"),
    ("język kannada (kn)", "język kannada (kn)"),
    ("język karaczajsko-bałkarski (krc)", "język karaczajsko-bałkarski (krc)"),
    ("język karakałpacki (kaa)", "język karakałpacki (kaa)"),
    ("język kaszmirski (ks)", "język kaszmirski (ks)"),
    ("język kaszubski (csb)", "język kaszubski (csb)"),
    ("język kataloński (ca)", "język kataloński (ca)"),
    ("język kazachski (kk)", "język kazachski (kk)"),
    ("język keczua (qu)", "język keczua (qu)"),
    ("język khmerski (km)", "język khmerski (km)"),
    ("język kirgiski (ky)", "język kirgiski (ky)"),
    ("język klingoński (tlh)", "język klingoński (tlh)"),
    ("język komi (kv)", "język komi (kv)"),
    ("język komi-jaźwiński (kom)", "język komi-jaźwiński (kom)"),
    ("język komi-permiacki (koi)", "język komi-permiacki (koi)"),
    ("język komi-zyriański (kpv)", "język komi-zyriański (kpv)"),
    ("język konkani (kok)", "język konkani (kok)"),
    ("język koptyjski (cop)", "język koptyjski (cop)"),
    ("język koreański (ko)", "język koreański (ko)"),
    ("język kornijski (kw)", "język kornijski (kw)"),
    ("język korsykański (co)", "język korsykański (co)"),
    ("język kri (cr)", "język kri (cr)"),
    ("język krymskotatarski (crh)", "język krymskotatarski (crh)"),
    ("język kumycki (kum)", "język kumycki (kum)"),
    ("język ladyński (lld)", "język ladyński (lld)"),
    ("język langwedocki (oci-lnc)", "język langwedocki (oci-lnc)"),
    ("język laotański (lo)", "język laotański (lo)"),
    ("język lezgiński (lez)", "język lezgiński (lez)"),
    ("język liguryjski (lij)", "język liguryjski (lij)"),
    ("język limburski (lim)", "język limburski (lim)"),
    ("język litewski (lt)", "język litewski (lt)"),
    ("język lombardzki (lmo)", "język lombardzki (lmo)"),
    ("język luksemburski (lb)", "język luksemburski (lb)"),
    ("język luo (luo)", "język luo (luo)"),
    ("język macedoński (mk)", "język macedoński (mk)"),
    ("język malajalam (ml)", "język malajalam (ml)"),
    ("język malajski (ms)", "język malajski (ms)"),
    ("język malediwski (dv)", "język malediwski (dv)"),
    ("język malgaski (mg)", "język malgaski (mg)"),
    ("język maltański (mt)", "język maltański (mt)"),
    ("język manx (gv)", "język manx (gv)"),
    ("język maoryski (mi)", "język maoryski (mi)"),
    ("język marathi (mr)", "język marathi (mr)"),
    ("język maryjski (chm)", "język maryjski (chm)"),
    ("język mazanderański (mzn)", "język mazanderański (mzn)"),
    ("język mikmak (mic)", "język mikmak (mic)"),
    ("język minnan (zh-min-nan)", "język minnan (zh-min-nan)"),
    ("język mongolski (mn)", "język mongolski (mn)"),
    ("język motu (meu)", "język motu (meu)"),
    ("język mołdawski (mo)", "język mołdawski (mo)"),
    ("język nahuatl (nah)", "język nahuatl (nah)"),
    ("język nauruański (na)", "język nauruański (na)"),
    ("język nawaho (nv)", "język nawaho (nv)"),
    ("język neapolitański (nap)", "język neapolitański (nap)"),
    ("język nepalski (ne)", "język nepalski (ne)"),
    ("język newarski (new)", "język newarski (new)"),
    ("język niemiecki (de)", "język niemiecki (de)"),
    ("język normandzki (nrm)", "język normandzki (nrm)"),
    ("język norweski (bokmål) (nb)", "język norweski (bokmål) (nb)"),
    ("język norweski (nynorsk) (nn)", "język norweski (nynorsk) (nn)"),
    ("język nowogrecki (el)", "język nowogrecki (el)"),
    ("język orija (or)", "język orija (or)"),
    ("język ormiański (hy)", "język ormiański (hy)"),
    ("język oromo (om)", "język oromo (om)"),
    ("język osetyjski (os)", "język osetyjski (os)"),
    ("język osmański (ota)", "język osmański (ota)"),
    ("język pali (pi)", "język pali (pi)"),
    ("język paszto (ps)", "język paszto (ps)"),
    ("język pendżabski (pa)", "język pendżabski (pa)"),
    ("język perski (fa)", "język perski (fa)"),
    ("język piemoncki (pms)", "język piemoncki (pms)"),
    ("język pikardyjski (pcd)", "język pikardyjski (pcd)"),
    ("język pirahã (myp)", "język pirahã (myp)"),
    ("język polski (pl)", "język polski (pl)"),
    ("język portugalski (pt)", "język portugalski (pt)"),
    ("język połabski (pox)", "język połabski (pox)"),
    ("język prowansalski (oc)", "język prowansalski (oc)"),
    ("język pruski (prg)", "język pruski (prg)"),
    ("język północnofryzyjski (frr)", "język północnofryzyjski (frr)"),
    ("język północnolapoński (sme)", "język północnolapoński (sme)"),
    ("język rarotonga (rar)", "język rarotonga (rar)"),
    ("język romansz (roh)", "język romansz (roh)"),
    ("język romski (rom)", "język romski (rom)"),
    ("język rosyjski (ru)", "język rosyjski (ru)"),
    ("język rumuński (ro)", "język rumuński (ro)"),
    ("język rundi (rn)", "język rundi (rn)"),
    ("język russenorsk (crp-rsn)", "język russenorsk (crp-rsn)"),
    ("język sardyński (sc)", "język sardyński (sc)"),
    ("język serbski (sr)", "język serbski (sr)"),
    ("język shelta (sth)", "język shelta (sth)"),
    ("język shona (sn)", "język shona (sn)"),
    ("język sindhi (sd)", "język sindhi (sd)"),
    ("język sko (sko)", "język sko (sko)"),
    ("język skolt (sms)", "język skolt (sms)"),
    ("język somalijski (so)", "język somalijski (so)"),
    ("język sorani (ckb)", "język sorani (ckb)"),
    ("język staro-cerkiewno-słowiański (cu)", "język staro-cerkiewno-słowiański (cu)"),
    ("język staro-wysoko-niemiecki (goh)", "język staro-wysoko-niemiecki (goh)"),
    ("język staroangielski (ang)", "język staroangielski (ang)"),
    ("język staroegipski (egy)", "język staroegipski (egy)"),
    ("język starofrancuski (fro)", "język starofrancuski (fro)"),
    ("język starogrecki (gr)", "język starogrecki (gr)"),
    ("język staroirlandzki (sga)", "język staroirlandzki (sga)"),
    ("język staronordyjski (non)", "język staronordyjski (non)"),
    ("język staroormiański (xcl)", "język staroormiański (xcl)"),
    ("język suahili (sw)", "język suahili (sw)"),
    ("język sumeryjski (sux)", "język sumeryjski (sux)"),
    ("język sundajski (su)", "język sundajski (su)"),
    ("język susu (sus)", "język susu (sus)"),
    ("język sycylijski (scn)", "język sycylijski (scn)"),
    ("język syngaleski (si)", "język syngaleski (si)"),
    ("język szkocki (sco)", "język szkocki (sco)"),
    ("język szkocki gaelicki (gla)", "język szkocki gaelicki (gla)"),
    ("język szorski (cjs)", "język szorski (cjs)"),
    ("język szwabski (gsw)", "język szwabski (gsw)"),
    ("język szwedzki (sv)", "język szwedzki (sv)"),
    ("język słowacki (sk)", "język słowacki (sk)"),
    ("język słoweński (sl)", "język słoweński (sl)"),
    ("język słowiński (csb-slo)", "język słowiński (csb-slo)"),
    ("język tabasarański (tab)", "język tabasarański (tab)"),
    ("język tadżycki (tg)", "język tadżycki (tg)"),
    ("język tagalski (tl)", "język tagalski (tl)"),
    ("język tahitański (ty)", "język tahitański (ty)"),
    ("język tajski (th)", "język tajski (th)"),
    ("język tamaszek (tmh)", "język tamaszek (tmh)"),
    ("język tamazight (tzm)", "język tamazight (tzm)"),
    ("język tamilski (ta)", "język tamilski (ta)"),
    ("język tashelhiyt (shi)", "język tashelhiyt (shi)"),
    ("język tatarski (tt)", "język tatarski (tt)"),
    ("język telugu (te)", "język telugu (te)"),
    ("język tigrinia (ti)", "język tigrinia (ti)"),
    ("język tonga (to)", "język tonga (to)"),
    ("język turecki (tr)", "język turecki (tr)"),
    ("język turkmeński (tk)", "język turkmeński (tk)"),
    ("język tuvalu (tvl)", "język tuvalu (tvl)"),
    ("język tuwiński (tyv)", "język tuwiński (tyv)"),
    ("język twi (tw)", "język twi (tw)"),
    ("język tybetański (bo)", "język tybetański (bo)"),
    ("język tybetański klasyczny (xct)", "język tybetański klasyczny (xct)"),
    ("język udmurcki (udm)", "język udmurcki (udm)"),
    ("język ujgurski (ug)", "język ujgurski (ug)"),
    ("język ukraiński (uk)", "język ukraiński (uk)"),
    ("język urdu (ur)", "język urdu (ur)"),
    ("język uwea (wls)", "język uwea (wls)"),
    ("język uzbecki (uz)", "język uzbecki (uz)"),
    ("język võro (fiu)", "język võro (fiu)"),
    ("język walijski (cy)", "język walijski (cy)"),
    ("język waloński (wa)", "język waloński (wa)"),
    ("język warajski (war)", "język warajski (war)"),
    ("język wczesny nowoangielski (emen)", "język wczesny nowoangielski (emen)"),
    ("język wenecki (vec)", "język wenecki (vec)"),
    ("język wepski (vep)", "język wepski (vep)"),
    ("język wietnamski (vi)", "język wietnamski (vi)"),
    ("język wilamowski (wym)", "język wilamowski (wym)"),
    ("język wolof (wo)", "język wolof (wo)"),
    ("język wysokoislandzki (art-is)", "język wysokoislandzki (art-is)"),
    ("język węgierski (hu)", "język węgierski (hu)"),
    ("język włoski (it)", "język włoski (it)"),
    ("język yupik środkowy (ypk)", "język yupik środkowy (ypk)"),
    ("język zachodnioflamandzki (vls)", "język zachodnioflamandzki (vls)"),
    ("język zarfatit (zrp)", "język zarfatit (zrp)"),
    ("język zazaki (zza)", "język zazaki (zza)"),
    ("język zelandzki (zea)", "język zelandzki (zea)"),
    ("język zulu (zu)", "język zulu (zu)"),
    ("język łaciński (la)", "język łaciński (la)"),
    ("język łatgalski (ltg)", "język łatgalski (ltg)"),
    ("język łotewski (lv)", "język łotewski (lv)"),
    ("język średnio-dolno-niemiecki (gml)", "język średnio-dolno-niemiecki (gml)"),
    ("język średnio-wysoko-niemiecki (gmh)", "język średnio-wysoko-niemiecki (gmh)"),
    ("język średnioangielski (enm)", "język średnioangielski (enm)"),
    ("język żmudzki (bat)", "język żmudzki (bat)"),
    ("język kałmucki (xal)", "język kałmucki (xal)"),
    ("język a-pucikwar (apq)", "język a-pucikwar (apq)"),
    ("język jakucki (sah)", "język jakucki (sah)"),
    ("język lazyjski (lzz)", "język lazyjski (lzz)"),
    ("język staroruski (orv)", "język staroruski (orv)"),
    ("język kurmandżi (kmr)", "język kurmandżi (kmr)"),
    ("język neo (neu)", "język neo (neu)"),
    ("język bislama (bi)", "język bislama (bi)"),
    ("język fryzyjski saterlandzki (stq)", "język fryzyjski saterlandzki (stq)"),
    ("język pensylwański (pdc)", "język pensylwański (pdc)"),
    ("język plautdietsch (pdt)", "język plautdietsch (pdt)"),
    ("Lingua Franca Nova (lfn)", "Lingua Franca Nova (lfn)"),
    ("język rusiński (rue)", "język rusiński (rue)"),
    ("język arczyński (aqc)", "język arczyński (aqc)"),
    ("język xhosa (xh)", "język xhosa (xh)"),
    ("język szerpa (xsr)", "język szerpa (xsr)"),
    ("romániço (roc)", "romániço (roc)"),
    ("wenedyk (art-wen)", "wenedyk (art-wen)"),
    ("język dari (prs)", "język dari (prs)"),
    ("język serbsko-chorwacki (hbs)", "język serbsko-chorwacki (hbs)"),
    ("język bugijski (bug)", "język bugijski (bug)"),
    ("język karelski (krl)", "język karelski (krl)"),
    ("język moksza (mdf)", "język moksza (mdf)"),
    ("język ama (amm)", "język ama (amm)"),
    ("język estremadurski (ext)", "język estremadurski (ext)"),
    ("język dołgański (dlg)", "język dołgański (dlg)"),
    ("język ewenkijski (evn)", "język ewenkijski (evn)"),
    ("język taos (twf-tao)", "język taos (twf-tao)"),
    ("język mirandyjski (mwl)", "język mirandyjski (mwl)"),
    ("język staroperski (peo)", "język staroperski (peo)"),
    ("język kabardyjski (kbd)", "język kabardyjski (kbd)"),
    ("język karatajski (kpt)", "język karatajski (kpt)"),
    ("język karaimski (kdr)", "język karaimski (kdr)"),
    ("język nieniecki (yrk)", "język nieniecki (yrk)"),
    ("język tigre (tig)", "język tigre (tig)"),
    ("język tarencki (roa-tara)", "język tarencki (roa-tara)"),
    ("język giliański (glk)", "język giliański (glk)"),
    ("język rohingya (rhg)", "język rohingya (rhg)"),
    ("język północny sotho (nso)", "język północny sotho (nso)"),
    ("język inupiak (ik)", "język inupiak (ik)"),
    ("język cziczewa (ny)", "język cziczewa (ny)"),
    ("język herero (hz)", "język herero (hz)"),
    ("język abua (abn)", "język abua (abn)"),
    ("język aczoli (ach)", "język aczoli (ach)"),
    ("język adjukru (adj)", "język adjukru (adj)"),
    ("język awestyjski (ae)", "język awestyjski (ae)"),
    ("język wotycki (vot)", "język wotycki (vot)"),
    ("język marszalski (mh)", "język marszalski (mh)"),
    ("język tumbuka (tum)", "język tumbuka (tum)"),
    ("język szan (shn)", "język szan (shn)"),
    ("język luganda (lg)", "język luganda (lg)"),
    ("język mohawk (moh)", "język mohawk (moh)"),
    ("język minangkabau (min)", "język minangkabau (min)"),
    ("język akan (ak)", "język akan (ak)"),
    ("język kantoński (yue)", "język kantoński (yue)"),
    ("język syryjski klasyczny (syc)", "język syryjski klasyczny (syc)"),
    ("język starosaksoński (osx)", "język starosaksoński (osx)"),
    ("język marwari (mwr)", "język marwari (mwr)"),
    ("język sango (sg)", "język sango (sg)"),
    ("język kanuri (kr)", "język kanuri (kr)"),
    ("hiri motu (ho)", "hiri motu (ho)"),
    ("język mon (mnw)", "język mon (mnw)"),
    ("język kildin (sjd)", "język kildin (sjd)"),
    ("język balijski (ban)", "język balijski (ban)"),
    ("język mansyjski (mns)", "język mansyjski (mns)"),
    ("język czukocki (ckt)", "język czukocki (ckt)"),
    ("język inari (smn)", "język inari (smn)"),
    ("język nahuatl klasyczny (nci)", "język nahuatl klasyczny (nci)"),
    (
        "język nahuatl centralnego Meksyku (nhn)",
        "język nahuatl centralnego Meksyku (nhn)",
    ),
    ("język maya (yua)", "język maya (yua)"),
    ("język kiliwa (klb)", "język kiliwa (klb)"),
    ("język megrelski (xmf)", "język megrelski (xmf)"),
    ("język pontyjski (pnt)", "język pontyjski (pnt)"),
    ("język ubychski (uby)", "język ubychski (uby)"),
    ("język ketyjski (ket)", "język ketyjski (ket)"),
    ("język buruszaski (bsk)", "język buruszaski (bsk)"),
    ("język mizo (lus)", "język mizo (lus)"),
    ("język eweński (eve)", "język eweński (eve)"),
    ("język nganasański (nio)", "język nganasański (nio)"),
    ("język koriacki (kpy)", "język koriacki (kpy)"),
    ("język południowoałtajski (alt)", "język południowoałtajski (alt)"),
    ("język mandżurski (mnc)", "język mandżurski (mnc)"),
    ("język mongolski klasyczny (cmg)", "język mongolski klasyczny (cmg)"),
    ("język umbundu (umb)", "język umbundu (umb)"),
    ("język hetycki (hit)", "język hetycki (hit)"),
    ("język zachodniopendżabski (pnb)", "język zachodniopendżabski (pnb)"),
    ("język kiribati (gil)", "język kiribati (gil)"),
    ("język tobati (tti)", "język tobati (tti)"),
    ("hindi fidżyjskie (hif)", "hindi fidżyjskie (hif)"),
    ("język gan (gan)", "język gan (gan)"),
    ("język cachurski (tkr)", "język cachurski (tkr)"),
    ("język lakota (lkt)", "język lakota (lkt)"),
    ("język buriacki (bua)", "język buriacki (bua)"),
    ("język niwchijski (mis)", "język niwchijski (mis)"),
    ("język nanajski (gld)", "język nanajski (gld)"),
    ("język ajnoski (ain)", "język ajnoski (ain)"),
    ("język zhuang (za)", "język zhuang (za)"),
    ("język czejeński (chy)", "język czejeński (chy)"),
    ("język lavukaleve (lvk)", "język lavukaleve (lvk)"),
    ("język aceh (ace)", "język aceh (ace)"),
    ("occidental (ie)", "occidental (ie)"),
    ("język rypuaryjski (ksh)", "język rypuaryjski (ksh)"),
    ("język bench (bcq)", "język bench (bcq)"),
    ("język franko-prowansalski (frp)", "język franko-prowansalski (frp)"),
    ("język pampango (pam)", "język pampango (pam)"),
    ("język bafia (ksf)", "język bafia (ksf)"),
    ("język norweski (riksmål) (nor)", "język norweski (riksmål) (nor)"),
    ("język samoański (sm)", "język samoański (sm)"),
    ("język krik (mus)", "język krik (mus)"),
    ("język dungański (dng)", "język dungański (dng)"),
    ("język lakijski (lbe)", "język lakijski (lbe)"),
    ("język antylski (acf)", "język antylski (acf)"),
    ("język północnojukagirski (ykg)", "język północnojukagirski (ykg)"),
    ("język yupik środkowosyberyjski (ess)", "język yupik środkowosyberyjski (ess)"),
    ("język chuuk (chk)", "język chuuk (chk)"),
    ("język botlichyjski (bph)", "język botlichyjski (bph)"),
    ("język kikuju (ki)", "język kikuju (ki)"),
    ("język mbukushu (mhw)", "język mbukushu (mhw)"),
    ("język tai lue (khb)", "język tai lue (khb)"),
    ("język diriku (diu)", "język diriku (diu)"),
    ("język lozi (loz)", "język lozi (loz)"),
    ("język ruanda (rw)", "język ruanda (rw)"),
    ("język godoberyjski (gdo)", "język godoberyjski (gdo)"),
    ("język czoktaw (cho)", "język czoktaw (cho)"),
    ("język tokelau (tkl)", "język tokelau (tkl)"),
    ("język mokeński (mhn)", "język mokeński (mhn)"),
    ("język mistek yosondúa (mpm)", "język mistek yosondúa (mpm)"),
    ("gallo (roa-gal)", "gallo (roa-gal)"),
    ("język ndyuka (djk)", "język ndyuka (djk)"),
    ("język bisznuprija-manipuri (bpy)", "język bisznuprija-manipuri (bpy)"),
    ("język liwski (liv)", "język liwski (liv)"),
    ("język meglenorumuński (ruq)", "język meglenorumuński (ruq)"),
    ("język igbo (ig)", "język igbo (ig)"),
    ("język selepet (spl)", "język selepet (spl)"),
    ("język molbog (pwm)", "język molbog (pwm)"),
    ("język tatana (txx)", "język tatana (txx)"),
    ("język rapanui (rap)", "język rapanui (rap)"),
    ("język niue (niu)", "język niue (niu)"),
    ("język massachusett (wam)", "język massachusett (wam)"),
    ("język tshangla (tsj)", "język tshangla (tsj)"),
    ("język itelmeński (itl)", "język itelmeński (itl)"),
    ("język dani zachodni (dnw)", "język dani zachodni (dnw)"),
    ("język dżerma (dje)", "język dżerma (dje)"),
    ("język kankuamo (qji)", "język kankuamo (qji)"),
    ("język purepecha (tsz)", "język purepecha (tsz)"),
    ("język jita (jit)", "język jita (jit)"),
    ("język talossański (tzl)", "język talossański (tzl)"),
    ("język kaingang (kgp)", "język kaingang (kgp)"),
    ("język kansa (ksk)", "język kansa (ksk)"),
    ("język komoryjski ngazidża (zdj)", "język komoryjski ngazidża (zdj)"),
    ("język kreolski gujański (gyn)", "język kreolski gujański (gyn)"),
    ("język bandżarski (bjn)", "język bandżarski (bjn)"),
    ("język ibański (iba)", "język ibański (iba)"),
    ("język kweński (fkv)", "język kweński (fkv)"),
    ("język istrorumuński (ruo)", "język istrorumuński (ruo)"),
    ("język fon (fon)", "język fon (fon)"),
    ("język mandinka (mnk)", "język mandinka (mnk)"),
    ("język maranao (mrw)", "język maranao (mrw)"),
    ("język pangasinan (pag)", "język pangasinan (pag)"),
    ("język doteli (dty)", "język doteli (dty)"),
    ("język amal (aad)", "język amal (aad)"),
    ("język miniafia-oyan (aai)", "język miniafia-oyan (aai)"),
    ("język ankave (aak)", "język ankave (aak)"),
    ("język arara parajski (aap)", "język arara parajski (aap)"),
    ("język algonkiński (alg)", "język algonkiński (alg)"),
    ("język arabela (arl)", "język arabela (arl)"),
    ("język południowojukagirski (yux)", "język południowojukagirski (yux)"),
    ("język yagua (yad)", "język yagua (yad)"),
    ("język zaparo (zro)", "język zaparo (zro)"),
    ("język futuna wschodni (fud)", "język futuna wschodni (fud)"),
    ("język mandejski (mid)", "język mandejski (mid)"),
    ("język sasak (sas)", "język sasak (sas)"),
    ("język suazi (ss)", "język suazi (ss)"),
    ("język mazahua (maz)", "język mazahua (maz)"),
    ("język kadazdański (dtp)", "język kadazdański (dtp)"),
    ("język seszelski (crs)", "język seszelski (crs)"),
    ("język pileni (piv)", "język pileni (piv)"),
    ("język afade (aal)", "język afade (aal)"),
    ("arvanitika (aat)", "arvanitika (aat)"),
    ("język !Kung (knw)", "język !Kung (knw)"),
    ("język omahijsko-ponkaski (oma)", "język omahijsko-ponkaski (oma)"),
    ("język klallam (clm)", "język klallam (clm)"),
    ("język maurytyjski (mfe)", "język maurytyjski (mfe)"),
    ("język śląski niemiecki (sli)", "język śląski niemiecki (sli)"),
    ("język tacki (ttt)", "język tacki (ttt)"),
    ("język tarifit (rif)", "język tarifit (rif)"),
    ("język ghadameski (gha)", "język ghadameski (gha)"),
    ("język nafusi (jbn)", "język nafusi (jbn)"),
    ("język zenaga (zen)", "język zenaga (zen)"),
    ("język taznatit (grr)", "język taznatit (grr)"),
    ("język warkalski (oua)", "język warkalski (oua)"),
    ("język santyjski (sce)", "język santyjski (sce)"),
    ("język siwi (siz)", "język siwi (siz)"),
    ("język sokna (swn)", "język sokna (swn)"),
    ("język hopi (hop)", "język hopi (hop)"),
    ("język wschodniokeresański (kee)", "język wschodniokeresański (kee)"),
    ("język zachodniokeresański (kjq)", "język zachodniokeresański (kjq)"),
    ("język zuni (zun)", "język zuni (zun)"),
    ("język amis (ami)", "język amis (ami)"),
    ("język elfdalski (ovd)", "język elfdalski (ovd)"),
    ("język południowomarkiski (mqm)", "język południowomarkiski (mqm)"),
    ("język północnomarkiski (mrq)", "język północnomarkiski (mrq)"),
    ("język siksika (bla)", "język siksika (bla)"),
    ("język odżibwe (oji)", "język odżibwe (oji)"),
    ("język dargijski (dar)", "język dargijski (dar)"),
    ("język starowalijski (owl)", "język starowalijski (owl)"),
    (
        "język nahuatl ze środkowej Huasteki (nch)",
        "język nahuatl ze środkowej Huasteki (nch)",
    ),
    ("język nahuatl z Puebli wyżynnej (azz)", "język nahuatl z Puebli wyżynnej (azz)"),
    (
        "język nahuatl z północnej Puebli (ncj)",
        "język nahuatl z północnej Puebli (ncj)",
    ),
    ("język huastek (hus)", "język huastek (hus)"),
    ("język pipil (ppl)", "język pipil (ppl)"),
    ("język otomi z doliny Mezquital (ote)", "język otomi z doliny Mezquital (ote)"),
    ("toki pona (art-pona)", "toki pona (art-pona)"),
    ("język neosalomoński (pis)", "język neosalomoński (pis)"),
    ("język knaan (czk)", "język knaan (czk)"),
    ("język komanczerski (com)", "język komanczerski (com)"),
    ("język aari (aiw)", "język aari (aiw)"),
    ("język swański (sva)", "język swański (sva)"),
    ("język hakka (hak)", "język hakka (hak)"),
    ("język mindong (cdo)", "język mindong (cdo)"),
    ("język wu (wuu)", "język wu (wuu)"),
    ("język bradź (bra)", "język bradź (bra)"),
    ("język assiniboine (asb)", "język assiniboine (asb)"),
    ("język mandan (mhq)", "język mandan (mhq)"),
    ("język atikamek (atj)", "język atikamek (atj)"),
    ("język kabowerdeński (kea)", "język kabowerdeński (kea)"),
    ("yumplatok (tcs)", "yumplatok (tcs)"),
    ("kriol australijski (rop)", "kriol australijski (rop)"),
    ("prakryt śauraseni (psu)", "prakryt śauraseni (psu)"),
    ("prakryt maharasztri (pmh)", "prakryt maharasztri (pmh)"),
    ("prakryt ardhamagadhi (pka)", "prakryt ardhamagadhi (pka)"),
    ("sindarin (sjn)", "sindarin (sjn)"),
    ("miskito (miq)", "miskito (miq)"),
    ("język wschodniokadazański (dtb)", "język wschodniokadazański (dtb)"),
    ("język środkowy bikolski (bcl)", "język środkowy bikolski (bcl)"),
    ("język bhodźpuri (bho)", "język bhodźpuri (bho)"),
    ("język matlatzinka (mat)", "język matlatzinka (mat)"),
    ("język starofryzyjski (ofs)", "język starofryzyjski (ofs)"),
    ("język tsonga (tso)", "język tsonga (tso)"),
    ("język venda (ven)", "język venda (ven)"),
    ("język mongorski (mjg)", "język mongorski (mjg)"),
    ("język bedża (bej)", "język bedża (bej)"),
    ("język selkupski (sel)", "język selkupski (sel)"),
    ("język achwaski (akv)", "język achwaski (akv)"),
    ("język jagnobijski (yai)", "język jagnobijski (yai)"),
    ("język bagulalski (kva)", "język bagulalski (kva)"),
    ("język tindyjski (tin)", "język tindyjski (tin)"),
    ("język czamalalski (cji)", "język czamalalski (cji)"),
    ("język khowarski (khw)", "język khowarski (khw)"),
    ("język hadżong (haj)", "język hadżong (haj)"),
    ("język maithili (mai)", "język maithili (mai)"),
    ("prakryt magadhi (pra)", "prakryt magadhi (pra)"),
    ("nahuatl z Orizaba (nlv)", "nahuatl z Orizaba (nlv)"),
    ("nahuatl ze wschodniej Huasteki (nhe)", "nahuatl ze wschodniej Huasteki (nhe)"),
    ("nahuatl z Tetelcingo (nhg)", "nahuatl z Tetelcingo (nhg)"),
    ("nahuatl z zachodniej Huasteki (nhw)", "nahuatl z zachodniej Huasteki (nhw)"),
    ("nahuatl z Temascaltepec (nhv)", "nahuatl z Temascaltepec (nhv)"),
    ("nahuatl z Guerrero (ngu)", "nahuatl z Guerrero (ngu)"),
    ("nahuatl z Durango (azd)", "nahuatl z Durango (azd)"),
    ("nahuatl z Mecayapan (nhx)", "nahuatl z Mecayapan (nhx)"),
    ("nahuatl z Morelos (nhm)", "nahuatl z Morelos (nhm)"),
    ("cerkiewnosłowiański (chu)", "cerkiewnosłowiański (chu)"),
    ("język tswana (tsn)", "język tswana (tsn)"),
    ("język yurok (yur)", "język yurok (yur)"),
    ("język kwama (kmq)", "język kwama (kmq)"),
    ("język chaladzki (klj)", "język chaladzki (klj)"),
    ("język puluwat (puw)", "język puluwat (puw)"),
]
